# 李宏毅-深度学习
https://www.bilibili.com/video/BV1b4411S7Ky/?spm_id_from=333.788.videocard.4

定义一个神经网络的三个步骤:
1. build nn
2. 确定cost function
3. 确定优化函数
![](deep_learning/img/dl01.png)

# Review basic structure
https://www.bilibili.com/video/BV1b4411S7Ky/?spm_id_from=333.788.videocard.4

## fully connected layer
Dense层在数学上看，就是 输入n为的向量Vn乘以一个矩阵，transform为m维的向量Vm，再经过激活函数做非线性变换

$$V_m=\sigma(V_n*W_{n*m})$$
### 符号表示
![](deep_learning/img/dl02.png)
![](deep_learning/img/dl03.png)
![](deep_learning/img/dl04.png)
![](deep_learning/img/dl05.png)
![](deep_learning/img/dl06.png)
![](deep_learning/img/dl07.png)

## Recurrent Structure
![](deep_learning/img/dr01.png)
### Deep RNN
![](deep_learning/img/dr02.png)

### bidirectional RNN 
![](deep_learning/img/dr04.png)

### pyramidal RNN
DeepRNN, 合并时间步长
![](deep_learning/img/dr05.png)
### Naive RNN
![](deep_learning/img/dn01.png)
### LSTM
![](deep_learning/img/dn03.png)
![](deep_learning/img/dn04.png)
![](deep_learning/img/dn06.png)
$\odot$表示element-wise的相乘 

向量Zi: input gate,决定输入能否流进去

向量Zf: forget gate, 决ct-1能否传入下一个时间点

向量Zo: output gate,
![](deep_learning/img/dn07.png)
![](deep_learning/img/dn08.png)


![](deep_learning/img/lstmresult.png)
### GRU
![](deep_learning/img/dn09.png)






## CNN | Pooling
https://www.bilibili.com/video/BV1b4411S7Ky/?p=2  开始时间 5min

Simplify nn(based on prior knowledge of the task

![](deep_learning/img/cnn01.png)
![](deep_learning/img/cnn02.png)

### conception
* receptive field  
    感受野，来自生物学概念
* filter(kernel)
    * filter(kernel) size  
        该filter覆盖的感受野的大小
    * Stride

### 卷积对应什么样的数学操作
CNN的卷积运算为何使用互相关而不是卷积 https://blog.csdn.net/appleyuchi/article/details/86574350

通俗理解【卷】积+互相关与卷积 https://blog.csdn.net/Sunny_HQ/article/details/80875664


一个二维矩阵经过卷积核处理后是什么结果？当kernel划过对应的感受野时，对应的数学运算叫互相关(即把kernel对应位置和其覆盖的位置对应相乘，然后结果求和)
![](deep_learning/img/cnnm01.png)

CNN的卷积运算并非数学定义的卷积

也就是说，CNN中的运算是不需要翻转卷积核的。

也就是说，CNN在处理图像时的卷积核是不需要翻转180°的

我们来用代码看下为什么？

In [3]:
#-*- coding:utf-8 -*-
import numpy as np
A=np.array([[0,0,0,0],\
                [0,0,30,0],\
                [0,60,0,0],\
                [0,0,0,0]])

B=np.array([[0.1,0.01],\
                [1,10]])
import scipy.signal
print("---------卷积结果---------------------")
print( scipy.signal.convolve(A,B,mode='valid'))
print("---------互相关结果---------------------")
print( scipy.signal.correlate(A,B,mode='valid'))

---------卷积结果---------------------
[[0.00e+00 3.00e+00 3.00e-01]
 [6.00e+00 3.06e+01 3.00e+02]
 [6.00e+01 6.00e+02 0.00e+00]]
---------互相关结果---------------------
[[  0.  300.   30. ]
 [600.   60.3   3. ]
 [  0.6   6.    0. ]]


因为卷积层后面连接的是池化层，
也就是说把卷积结果得到的矩阵中，
选取矩阵中数值最大的元素作为保留，矩阵中其余元素一律删除。

所以我们可以看到：
上述代码的
卷积结果中的最大值
与
互相关结果矩阵中的最大值
都是600
因此后面maxpooling层进行池化后得到的值也都是600.

如果后面接全连接层，那么
上面两个矩阵全部flatten以后输入dense层，几乎完全一致，也不影响建模

结论：
CNN中使用卷积或互相关，对于
的贡献是一致的，都是获取像素最大的那个值，
因此可以使用卷积，也可以使用互相关，
但是为了代码的高效，直接使用“互相关”即可。

### Example-1D signal+Multiple Channel
![](deep_learning/img/cnn03.png)
![](deep_learning/img/cnn04.png)
![](deep_learning/img/cnn05.png)
![](deep_learning/img/cnn06.png)
![](deep_learning/img/cnn07.png)
![](deep_learning/img/cnnp01.png)

# Computational Graph
https://www.bilibili.com/video/BV1b4411S7Ky/?p=3
![](deep_learning/img/cg01.png)


## Feedforward Network 前馈网络的计算图画法
$$y=\sigma(W^L...\sigma(W^2\sigma(W^1x+b^1)+b^2)...+b^L)$$
![](deep_learning/img/cgl01.png)

### Loss Function of Feedforward Network
![](deep_learning/img/cgl02.png)

## Gradient of Cost Function
![](deep_learning/img/cg02.png)

在反向求微分时，遇到的问题是: C是标量，而y, z2, a1, z1等都是向量，标量对向量，向量对向量如何求偏微分呢？

### Jacobian Matrix
向量对向量求偏微分的结果，是一个矩阵，行数是分子向量的维度，列数是分母向量的维度
![](deep_learning/img/cg03.png)

### 实例求解
#### $\frac{\partial C}{\partial{y}}$
以loss function为cross entropy loss为例说明
$$CrossEntropyLoss: l(\vec y, \vec{\hat y})=-\sum_{i=1}^n\hat{y_i}ln(y_i)=-ln(y_r)$$，其中$\hat{y_i}$的第r维为1，其余为0
其中$\vec y$为预测值，$\vec{\hat{y}}$为真实值, 

$$\frac{\partial C}{\partial{y}}=[0 ... \frac{-1}{y_r} ...]$$
![](deep_learning/img/cgr01.png)

#### $\frac{\partial y}{\partial z^2}$
以\sigma为sigmoid函数为例
$$\vec y=[y_1\ y_2\ ...]=[\sigma(z_1^2)\ (\sigma z_2^2)\ ....]$$
![](deep_learning/img/cgr02.png)

#### $\frac{\partial z^2}{\partial a^1}$
$$\frac{\partial z^2}{\partial a^1}=W^2$$
![](deep_learning/img/cgr03.png)

#### $\frac{\partial z^2}{\partial W^2}$
把矩阵拉平为向量
![](deep_learning/img/cgr04.png)

#### $\frac{C}{\partial W^1}$
![](deep_learning/img/cgr05.png)

## Computational Graph for Recurrent Network
输入为时间步长为1步
![](deep_learning/img/cgr11.png)
输入为时间步长为3步
![](deep_learning/img/cgr12.png)


![](deep_learning/img/cgr14.png)
![](deep_learning/img/cgr15.png)

# Attention and Transformer
https://www.bilibili.com/video/BV1b4411S7Ky?p=8  25min attention  

传统的seq2seq模型，先由encoder把一个句子编码为一个向量，然后把这个向量作为decoder的输入，每次时间步都输入，直到decoder产生结束标志为止。

传统的seq2seq模型的问题是 整个句子被编码为一个向量，decoder看到的是相同的。
![](deep_learning/img/att00.png)
而以机器翻译为例，输入句子的不同部分对输出的影响是不同的。所以引出了attention
![](deep_learning/img/att01.png)
z0是一个初始的向量，其参数可以学出来
![](deep_learning/img/att02.png)
z1是把c0丢进decoder中rnn的隐层输出，
![](deep_learning/img/att03.png)
把z1再和h1...等算一次得到c1
![](deep_learning/img/att04.png)
![](deep_learning/img/att06.png)

# 花书
http://www.deeplearningbook.org/